### PR TITLE
Add the `LICENSE.md` file from OM.jl

### LINKED ISSUE #61: Add OSI-approved license to OMJulia top level folder
Currently https://github.com/JuliaRegistries/General/pull/58444 fails, because of the missing license file, so we can't update our OMJulia version in the Julia general regestry.

OMJulia source files are using the [OSMC-PL](https://www.openmodelica.org/developersresources/contributor-license-agreement?id=56:full-license) license, see e.g. https://github.com/OpenModelica/OMJulia.jl/blob/master/src/OMJulia.jl#L1-L27.

Our OSMC-PL license is problematic for adding OMJulia to the general registry since it is not part of the [OSI-approved license](https://opensource.org/licenses/alphabetical).

Is there any reason to not just use a license that is OSI-aproved and allowes other to change OMJulia.jl? E.g. MIT license.
This package is only a API for OpenModelica and OpenModelica is not shipped with it.
So all generated code by omc is still under OSMC-PL license.

Or we use GPL-3.0, but then nobody is allowed to change OMJulia.

### PR DESCRIPTION
**Pull request by DilumAluthge**
This PR adds the `LICENSE.md` file from the https://github.com/JKRT/OM.jl/pull/37 branch.

Fixes #61

### CODE REVIEW

**Comment by DilumAluthge** [comment]
cc: @JKRT @viralbshah

**Comment by JKRT** [comment]
@casella I think this should be OK s.t we can register OMJulia; the package is a wrapper around omc.
This would also close the following ticket https://github.com/OpenModelica/OMJulia.jl/issues/61

What do you think?

**Comment by ViralBShah** [comment]
This will also allow us to register the package in the Julia General registry, making it easy for others to download and use.

**Comment by casella** [comment]
LGTM. The only missing point is explaining that only half of OSMC-PL is OSI approved, i.e. GPL v3

**Comment by casella** [comment]
@DilumAluthge I'm sorry but I messed up. This is not the right license, you need the runtime OSMC-PL-RT license instead. I'll take care of that ASAP.

**Pull request merged**
